[package]
name = "eve-validator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonschema = "0.13"
clap = { version = "3.1.6", features = ["derive"] }
serde_json = "1"
