[package]
name = "eve-validator"
version = "0.1.0"
edition = "2018"

[dependencies]
jsonschema = { version = "0.17", default_features = false }
clap = { version = "3.1.6", default_features = false, features = ["std", "derive"] }
serde_json = "1"
